### ISSUE TITLE
Dependency on `typeorm`

### ISSUE THREAD

**Issue by j** [marcj/marshal.ts#19]
I know there's a similar issue to this (or perhaps it's pretty much the same), but for my sanity, I'm wondering why `typeorm` is a dependency.  `typeorm` + `mongodb` has so many issues.  I want to plug this into my https://github.com/j/type-mongodb library (ironically, when I started this mapper, my first idea was to do JIT as well, but didn't to keep it simple for now).  WIth this package, I'm going to switch it over to using Marshal.ts.  With that said, it'd be nice to not be able to pull in `typeorm` when using the mongo mapper utility functions.  Maybe `marshal-mongo` should just be the core of mongo logic and can have a `marshal-typeorm` package utilizing it.

**Comment by marcj** [comment]
You're right. Let's move that to `marshal-mongo`. 

If you're interested in merging your project with marshal-mongo I'd love to talk with you, since I plan to create `marshal-orm`, which will pretty much be Typeorm, but with full mongodb support (with relations/joins, like marshal-mongo currently) and probably a couple of dozens times faster.

**Comment by marcj** [comment]
Oh, sorry, I misunderstood. `marshal` package has no `typeorm` dependency, so you probably want to use `marshal-mongo` and don't want to have typeorm there as dependency. Currently, the connection-handling is based on typeorm. This could be easily removed, but takes a couple of minutes to test. Then we could move that `getTypeOrmEntity` to another package or simply drop it.
What's your plan in using marshal-mongo with your library? I ask because the major features overlap.

**Comment by j** [comment]
Mainly just to remove the mapping aspect out of my library.  But the mapping aspect is pretty much 90% of why I wrote it.  So it'd essentially turn my library into just a repository layer on top of your library.  I'm not sure how I was going to go about it.  I just came across this library and my wheels started spinning on it.

**Comment by marcj** [comment]
Alright, I just removed typeorm entirely, see https://github.com/marcj/marshal.ts/commit/6bdf78f0ceaafa7caf4432b464c7d53f386d19b3. 
The dependency isn't necessary anymore, it was only used historically because I planned to use its repository/connection-manager/entity-manager, but since that would degrade the performance promises of Marshal I stopped doing it and was only using its connection-manager, which was unnecessary. Also I implemented already a lot of ORM stuff in marshal-mongo myself which duplicates stuff from typeorm (although the mongodb support of Typeorm is basically non-existent), but that's still WIP. When I integrated the Unit-of-Work with batch inserting then it's ready for prime-time and I'll rename the package to `marshal-orm` while decoupling mongo's hardcoded stuff. However, I'm still searching for a good and performant grouped topological sort algorithm in JS before I can start the UoW. I guess I have to write it again myself, because I wasn't lucky yet.

**Comment by j** [comment]
Haha, yep, good luck!  There's really no true ODM for node.js + mongo.  I'd like to see entity persistence with dirty field checking to perform partial field updates instead of entire document updates (on nested & nested arrays as well).

I'll be on the lookout for what you come up with.

**Comment by marcj** [comment]
Thanks! I released the changes already, so I'm closing this one.

Dirty checking with partial updates (core for this is already there), UoW, Repository pattern, entity-manager/active-record pattern are definitely the features I consider inevitable for an ORM/ODM this scale. Whether a migration feature is necessary or not is something I don't know yet. I know from PropelORM that this is by far the most hairy feature that costs a lot of time, and is very unsexy work. Relation and querybuilder stuff is however already covered and implemented for Mongo. Documentation is little to non-existent tho. Maybe a little website helps here better than a readme with thousand lines.
It's actually interesting that there is no good ODM for mongo in TS. Even mongoose is terrible, and Typescript has little to no support. I kind of wonder what the performance of TypeOrm is, with mongo and with PostreSQL/MySQL, I assume not so exciting. Also sending filtered database records to the client via JSOn while deserializing there with the same model declaration is most of the time completely missing in the big picture of those libraries - I have to serialize manually to transport the data to the client and there to deserialize manually. Terrible. A situation I find personally very inefficient. There are obviously ways to make the development process of full-stack apps for many ten thousand developers way easier.

Let me know if you are interested in participating.
