### ISSUE TITLE
Question about nested refs 

### ISSUE THREAD

**Issue by cabe7** [marcj/marshal.ts#30]
Hi Marc,

In the example below, is there a way with the current decorators to make _owner: Data.owners.a_ in the nested objects a reference to the instance in the top level _owners_ object?

Currently when I _classToPlain()_  -->  _plainToClass()_ it creates a new instance of Owner each time (each with the same data as owner.a)
i.e. currently...
owners.a !== collections.c.owner
owners.a !== collections.c.items[0].owner

but I need  ===

```
Data
|
|-owners {
    a: Owner
    b: Owner
  }
|
|-collections {
    c: Collection
    d: Collection
        |
        |- owner = Data.owners.a
        |- items [
             0: Item
             |
             |-owner = Data.owners.a
           ]
  }
```

This is simplified version of the code... 

```javascript
class Data {
  @f.map(Owner) public owners;
  @f.map(Collection) public collections;

  constructor() {}

  // in some init method
  this.owners = {
    a: new Owner;
    b: new Owner;
  }
  this.collections = {
    c: new Collection(this.owner.a);
    d: new Collection(this.owner.b); 
  }
}

class Collection {
  @f.type(Owner) public owner; // *toClass creates new copy of owners.a *
  @f.array(Item) public items;

  constructor(owner) {
    this.owner = owner;
    this.items = [];
  }
  // in some init method
  this.items.push(new Item(this.owner))
}

class Item {
  @f.type(Owner) public owner; // *toClass creates new copy of owners.a *

  constructor(owner) {
    this.owner = owner;
  }
}
```

Manged to get @ParentReference() with @f.forward working nicely with a parent-child elsewhere in the code, but this is proving a bit more tricky!

Many thanks

**Comment by marcj** [comment]
Yes, that's expected behavior. `plainToClass` does not have identity tracking implemented and thus does not differentiate between those objects. However, the mongo package has this functionality as its an inherent property of relational data to support instance pooling. So your best bet is for the moment to try `mongoToClass` instead of `plainToClass`, but keep in mind that binary types won't work here since mongo's storage encodes them differently. To make this functioning you need to mark a primary key in owner model using `@f.primary()`. If you don't have a id at hand you can use uuids.

```
import {f, uuid} from '@marcj/marshal';

class Owner {
   @f.uuid().primary() id: string = uuid();
}
```

Also I'd like to note that your current approach sends duplicated data. If the owner model gets bigger you're using more bandwidth than necessary. Also it seems you're violating separation of concerns principle here which is the cause that brings you to this dilemma. My tip for you is to define a single owner of the `Owner` object and use references everywhere else. You have as I see two ways:

1. Keep the owner of `Owner` at `Data::owners` array, and replace `Collection::owner` with an reference `Collection::ownerId`. This also changes the constructor of course. To have things handy, you could create a new method at `Data` called `createCollection` where you pass an owner object and it automatically create the collection with the correct owner id.
2. Keep the owner of `Owner` at `Collection::owner`. This makes `owners` basically useless since you have that data already in `collections`. You could replace `owners` with a getter

```typescript
get owners(): Owner[] {
   return this. collections.map(v => v.owner);
}
```

What suits better to you depends on your business model and logic.

**Comment by cabe7** [comment]
Thanks for the swift reply.

Good to know that about mongoToClass. I'm reconstructing with toClass in the browser though - mongoToClass() is server side only right? 

But anyway, you're right about the duplication, and route 1 is a sensible approach - good tip. 

One further question. How would you suggest handling conditional substitution of objects (e.g. so that the JSON contains an alternative 'placeholder' instance for some Items when sending to specific recipients , e.g.
```javascript
// Let there be a Item::visibleBy property

// For each Item in the array when performing classToPlain()...
if (thisItem.visbleBy === recipientId) {
// serialize normally
}
else {
 // - substitute for some other instance of Item, (or directly specify
 //   property values to be used instead of the actual ones)
}
```
Is this something that can be achieved with Marshal during classToPlain(), or do you suggest implementing this afterwards, working directly on the JSON?

**Comment by marcj** [comment]
@cabe7 do you have an example for that use-case with actual (model) code? I don't understand yet the use-case, but modifying the json object after classToPlain is probably the way to go.

**Comment by cabe7** [comment]
No code for this yet, but use case would be for a game, where the server uses classToPlain() to send the initial game state (which includes all player units) to the clients.

However, the JSON for player 1 should for example not include the data for player 2 pieces that are not in player 1 territory (and visa versa).

There are several way to approach this but I wondered if there was some functionality I was missing  that accomplish this (as there seems to be a few things  in the marshal code that are not documented). Modifying the JSON is straightforward enough I'll go down this route for now.

Good work on this library by the way!

**Comment by marcj** [comment]
I see, indeed that's out of scope of Marshal and is better placed in your business logic, either before you use classToPlain or after. I tend to do it before:

```
class DataState {
    scopeToPlayer(player: Player){ 
      const state = clone(this);
      //todo: remove all data from `state` that isn't accessible by given player
      return state;
   } 
}

const state = new DataState();
response.send(classToPlain(state.toJsonForPlayer(currentPlayer)));
```

From by experience working on the class instances as long as you can and only right before sending to the client use the serializer greatly increases readability and maintainability.

**Comment by cabe7** [comment]
Thanks, I appreciate the input
