### ISSUE TITLE
JIT compiled validators should be much much faster

### ISSUE THREAD

**Issue by shlomiassaf** [marcj/marshal.ts#37]
In the intro you perform a comparison against class-transformer which is probably at the lowest end of validators in terms of performance...

You should actually compare to other JIT libraries and not to composition library.

`ts-json-validator` (avj) or `quartet`

They both have a huge advantage over `marshal.ts`

![image](https://user-images.githubusercontent.com/5377501/82601819-d0f18b80-9bb8-11ea-91f3-4116b27cd248.png)

Since the top 3 libraries are JIT, you can see the gap.

> Note that JIT libraries do excel at benchmarks, less at realtime world scenarios since JIT libraries LOVE it when the same validator function is running over and over, getting inlined all the way.

-----

BTW, I believe that if you can shorten the amount of function calls done from calling to perform validation and until returning a result you will get better benchmark results.

**Comment by marcj** [comment]
So, any link to the benchmark? I had something like that with another library in a benchmark as well. It was only faster for a very very basic type check, and as soon as realistic checks are involved the performance drop was enourmouse - which did not happen in Marshal. 

However, I doubt that those numbers are realistic. Either Marshal was not correctly used or the benchmark basically does almost nothing.

So without link and code to the benchmark, I can't do anything about your comment.

**Comment by marcj** [comment]
> Note that JIT libraries do excel at benchmarks, less at realtime world scenarios

This is simply not true. Maybe in certain areas where it can happen that many many different JIT functions are generated depending on the use-case. However, in validation this is not the case since you ususally don't have tenthousands of different schemas, so a JIT validation should always be way faster, also and especially in real-world scenarios. Except of course if the JIT engine is built in a way that would generate different code depending on the actuall call and its data. This is however a design error, and has mothing to do with a drawback of JIT engines.

**Comment by marcj** [comment]
Ah I see, you talk about the linked benchmark repo. Well I talked with the author already that he is using Marshal wrong. Marshal has 2 main features: Validating and transforming data. The author uses both features at the same time for a simple validation check, although transforming is traditionally way slower and not necessary for validation. In other libraries like ts-json-validator (avj) or quartet he uses only the validation feature. So clearly the benchmark is flawed. I tried to correct it in https://github.com/moltar/typescript-runtime-type-benchmarks/pull/148, but the author refuses to merge since a totally different topic type guarding doesn't meet his criteria.

Also here is the issue where I explain in detail why his benchmark is fundamentally flawed for validation. https://github.com/moltar/typescript-runtime-type-benchmarks/issues/149. The consensus was 
> Ok, I missed that you even stated in the README that this library is not supposed to be a validation benchmark, but just a type checker

So, the linked repo is not actually a validation benchmark, but just a very simple runtime type checker. It's very misleading to say now that Marshal is slower in validation, when you really talk about a very specific subset, namely just type checking.

I'm going to remove the link as its highly misleading and instead link to the benchmark I use in Marshal's test suite.

**Comment by marcj** [comment]
I just added quartet to the [validation benchmark suite](https://github.com/marcj/marshal.ts/blob/master/packages/benchmark/validation.spec.ts):

```
100000 x benchmark validation jit on plain 11.493452000000161 ms 0.00011493452000000162 per item

100000 x benchmark validation ajv 311.0323880000001 ms 0.0031103238800000007 per item

100000 x benchmark validation quartet 22.230227999999897 ms 0.00022230227999999898 per item
```

So, I'm closing this one.

**Comment by shlomiassaf** [comment]
I'v updated the tests and re-ran them with JIT and OLD marshal versions

![image](https://user-images.githubusercontent.com/5377501/82625055-d49f0580-9bec-11ea-8bdc-a5ecf4929c91.png)

Still, not close

I'm dont know what your'e doing to get these results....

**Comment by shlomiassaf** [comment]
You can see the different benchmark code here

https://github.com/shlomiassaf/pebula-node/tree/master/packages/touchstone/demo/src/cases

Please correct me if i'm wrong...

**Comment by marcj** [comment]
Are you trolling? You literally added to Marshal's case additional validation rules like isNegative etc which you did not add to quartet etc and wonder why the latter is faster?

I linked the benchmark code so you can clearly see that Marshal is in actual real-world use-cases (where nobody only checks for types, but also for content stuff, like arrays, string length, number range...) way way faster. In synthetic benchmarks where only types are checked is Marshal slower - as it was not tuned for those rather exotic use-cases.
