### ISSUE TITLE
Status of discriminator support

### ISSUE THREAD

**Issue by kkelk** [marcj/marshal.ts#38]
Thanks for all of your work on this library, I've been searching for a good solution to this problem, and this is very close to all I need. The major feature it's missing for me is "discriminator support" as listed in the TODO section of the README, and so I wondered if there's any work in progress or a timeline/effort estimate for this feature?

Alternatively, is there a plausible workaround that we can implement on our side? I had a look at implementing a custom serialization target, but that didn't strike me as the right tool - although I could easily be missing something.

Thanks!

**Comment by marcj** [comment]
Not yet planned or implemented. What would be a good user-side API to support that feature, wdyt?

**Comment by kkelk** [comment]
I'm new to typescript, so forgive me if this doesn't make sense or is technically impossible, but I was hoping that something like the following would be possible (using a contrived example):

```typescript
import {f, validatedPlainToClass} from "@marcj/marshal";

abstract class Animal {
    @f.discriminator
    animalType: string;

    @f
    age: number;
}

@f.discriminator('animalType', 'dog')
class Dog extends Animal {
    @f
    barkVolume: number;
}

@f.discriminator('animalType', 'bird')
class Bird extends Animal {
    @f
    wingspan: number;
}

const instance = validatedPlainToClass(Animal, {
    animalType: 'bird',
    age: 3,
    wingspan: 4
});
```

Open to debate on whether this is the best API for all use-cases, but I like that it marks the discriminator value on the class itself rather than the base class (like `class-transformer` requires) because it's less likely to be forgotten when adding a new sub class. Note also that `age` (and its `@f` decoration) is inherited here, which seems pretty important when supporting discriminators over subclasses like this.

What do you think of this? If supporting arbitrary union types is important I suspect the API gets a fair bit more complex, but just having sub-classes solves my problem and I assume many others.

**Comment by LifeIsStrange** [comment]
Just to say our enterprise needs this support in order for us to use this lib instead of class transformer :/

**Comment by kkelk** [comment]
> Just to say our enterprise needs this support in order for us to use this lib instead of class transformer :/

Thanks @LifeIsStrange - what do you think of the API I suggested above? Would that solve your problem too, or do you have another idea in mind?

**Comment by LifeIsStrange** [comment]
@kkelk while the proposed API works fine for the given example, I currently think it is inferior to the API of class transformer:
https://github.com/typestack/class-transformer#providing-more-than-one-type-option
If we try to translate your proposed API to their example we can see the following shortcomings (mostly due to the fact that the example has nesting)

given the following json that we want to serialize into an Album class containing a topPhoto union type
```json
{
    "id": 1,
    "name": "foo",
    "topPhoto": {
        "id": 9,
        "filename": "cool_wale.jpg",
        "depth": 1245,
        "__type": "underwater"
    }
}
```
existing class transformer API:
```typescript
import {Type, plainToClass} from "class-transformer";

export abstract class Photo {
    id: number;
    filename: string;
}

export class Landscape extends Photo {
    panorama: boolean;
}

export class Portrait extends Photo {
    person: Person;
}

export class UnderWater extends Photo {
    depth: number;
}

export class Album {

    id: number;
    name: string;

    @Type(() => Photo, {
        discriminator: {
            property: "__type",
            subTypes: [
                { value: Landscape, name: "landscape" },
                { value: Portrait, name: "portrait" },
                { value: UnderWater, name: "underwater" }
            ]
        }
    })
    topPhoto: Landscape | Portrait | UnderWater;

}

let album = plainToClass(Album, albumJson);
// now album is Album object with a UnderWater object without `__type` property.
```
The json has a __type field that will be the topPhoto type value

versus a rough implementation with the proposed API:
```typescript
import {f, validatedPlainToClass} from "@marcj/marshal";

abstract class Photo {
    @f
    id: number;
    @f
    filename: string;

    @f.discriminator
    typeOfPhoto: string;
}

@f.discriminator('typeOfPhoto', 'landscape')
class Landscape extends Photo {
    @f
    panorama: boolean;
}

@f.discriminator('typeOfPhoto', 'portrait')
class Portrait extends Photo {
    @f
    person: Person;
}

@f.discriminator('typeOfPhoto', 'underwater')
export class UnderWater extends Photo {
    @f
    depth: number;
}

class Album {
    @f
    id: number;
    @f
    name: string;

    constructor() {
        this.topPhoto = validatedPlainToClass(Photo, {
                            typeOfPhoto: ???,
                            // fields shouldnt be hardcoded but instead retrieved automatically from the json
                        });
    }

    topPhoto: Landscape | Portrait | UnderWater;
}
```
(feel free to point mistakes in translation)

overall I find the class transformer API in comparison:
1) less verbose
 1.1) no need for @f annotations (might be a current limitation of marshal.ts and not of necessarilly of the proposal)
2) not need for the pervasive field typeOfPhoto
3) @Type is more centralized hence slightly more refactorable and readable
4) less reliance on type hardcoded as string which has no IDE support (goto) and is breakable on renaming
5) less obvious, I'm not confident my translation would work ( 
I would first call validatedClassToPlain for deserializing Album which would automagically call the (needed) constructor for deserializing the nested field topPhoto ? but how would I pass the json fields and type to the second validatedPlainToClass without hardcoding the parameters as I can with class transformer API ? )

This is why I conclude that the current class transformer API here is "superior" and should be reused (but maybe it could be improved ?).
Of course I might have misunderstandings and I have not considered enough kind of use cases/examples to be certain of what the best API would look like.

**Comment by maricn** [comment]
disclaimer: _Sorry for commenting on the closed issue, but I believe you can give the best support + it's on topic._

I'm interested can the existing API support the case when **discriminator is defined outside of discriminated class**, like so:
```
class CreatePhotoDTO {
    @f
    meta: MetaDTO;
    @f.union(LandscapePhotoDTO | PortraitPhotoDTO)
    content: LandscapePhotoDTO | PortraitPhotoDTO = 'landscape';
}

class MetaDTO {
    @f.discriminant()
    photoType: string = 'landscape';
}

class PhotoDTO {
    @f
    width: number;
    @f
    height: number;
}

class LandscapePhotoDTO extends PhotoDTO {
    @f
    panorama: boolean;
}

class PortraitPhotoDTO extends PhotoDTO {
    @f
    person: Person;
}
```
