### ISSUE TITLE
[Question] Dependency on typeorm ?

### ISSUE THREAD

**Issue by jeremyben** [marcj/marshal.ts#5]
Your package is really interesting to me in its relations to mongo.

One thing confuses me is its relations to typeorm as an intermediary wrapper (or not) for mongo connection and entity handling.

- Is Typeorm a required dependency for other than the `createConnection` part ?
- Do I still need to annotate my classes with the Entity decorator, or any other decorator from Typeorm, and also still extend from the BaseEntity ?

I see that you go straight for the mongo db instance instead of using the typeorm query manager for your queries.

#### Why I ask you this ?
We are building an app using typeorm for Mongo, and it has a lot of quirks and inconsistencies as it was built as an afterthought into Typeorm.
We're considering reimplementing it, and I just stubbled upon your package, which seems to almost perfectly fit the bill.

#### _Side note_

I know it's bikeshedding, but your inconsistent use of yoda notation confuses me as well 😄 . Is there a reason other than habit from another language ?

**Comment by marcj** [comment]
> Is Typeorm a required dependency for other than the createConnection part ?

It's mainly used for the connection abstraction. However, it is also needed for the `getTypeOrmEntity` method, which returns a `{EntitySchema} from 'typeorm'`, which you need to sync indices to mongodb during connection establishing or generating schema migration file.

> Do I still need to annotate my classes with the Entity decorator, or any other decorator from Typeorm, and also still extend from the BaseEntity ?

There's no need to decorate the entity with any Typeorm decorator. They won't be used by Marshal in any way.  However, you're allowed to use them if you want to use them in TypeORM. But for most uses-cases with Marshal+Mongodb there's no need to add typeorm indices. 

Side note:

You're completely right, this is very inconsistent and due to linter not at all necessary anymore. I should probably just don't use it anymore. :D

**Comment by marcj** [comment]
I added a note in the README so it should be clearer.

**Comment by jeremyben** [comment]
Ok thanks for that !

To be honest, I'm still not sure about the responsabilities of each of your packages. If you intend to provide a replacement for the whole "typestack" (class-validator, class-transformer, class-sanitizer, typeorm), I think you should modularize in the same way.

I thought that core package was the equivalent of class-transformer, but I see some decorators in there that deal with database, with validation and such. Isn't that leaky ? Maybe I'm too influenced by the typestack, but their abstractions are on spot, when it comes to concerns.

I think you did a wonderful job to improve on the typestack, it's just that the overall "separation of concern" of your packages leaves me confused.

If I have some time, I might try a PR with what I said.

**Comment by marcj** [comment]
It's a different approach. What you do with typestack is you have for your frontend an entity class decorated with class-transformer and for your backend/database your have another one decorated with typeorm's decorators, but with the same fields. Maybe you have only one class but doubled decorated with class-transformer and typeorm at the same time. This is redundant and not necessary.

Marshal introduces the concept of decorate once and use the same entity class everywhere. That's why there are database decorators in core, and there will be many more like for relations, and such.

Validation is in core because it's no concern of a database to validate, but about ever place where untrusted data can be, which means everywhere.

Marshal does replace all of class-transformer, class-validator, and on top of typeorm introduces a simpler mongodb abstraction. 

If you modulize the same way as typestack does, you suffer from the same consequences, which means you have to decorate for typeorm differently than for class-transformer where you end up having multiple entity classes for the same domain model. So, I don't think there is a need to separate further. But if you have an uncovered use-case, let me know.

In the future, marshal-mongo will be replaced by marshal-database package, which allows you to adapt to typeorm's approach, namely the entity manager, repositories and migrations etc, but still have only one entity class defined and decorated via Marshal.

I'll update the docs tonight to make that approach with its advantages more clear.

**Comment by jeremyben** [comment]
Ok I think I get it !

All the decorators are in core package, but the actual marshalling, on fields using specific server-side decorators (for example the ones related to mongo), happens elsewhere, using another package.
So your entity files can stay isomorphic and not import packages with code dedicated to server-side marshalling.

If so, that's brillant 🙂

**Comment by marcj** [comment]
You got it precisely :)
