### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by eyexpo-thomas** [marcj/marshal.ts#7]
Can we publish this package on npm? I created [a PR here](https://github.com/marcj/marshal.ts/pull/6/commits/1a99ade08e1570f211efbe29a68275c20b1953df) to tidy-up the package.json a bit.

**Comment by eyexpo-thomas** [comment]
By the way, there is a problem with the tests, running `npm t` yields this output: https://gist.github.com/eyexpo-thomas/362c8c12f3d226e5ac2884a91e618a90
because none of the imports from '@marcj/marshal/tests/entities' work.

**Comment by marcj** [comment]
What do you mean? It is published. Packages are organized using Lerna, see `packages/` folder.
Tests run as well, see https://travis-ci.com/marcj/marshal.ts. See https://github.com/marcj/marshal.ts/blob/master/.travis.yml#L12-L17 on how to run tests. You need to run lerna bootstrap before otherwise packages are not linked.

**Comment by eyexpo-thomas** [comment]
>What do you mean? It is published.

Can someone provide me with the link on npmjs.com ?

**Comment by marcj** [comment]
There's a link in the readme. https://www.npmjs.com/package/@marcj/marshal

**Comment by eyexpo-thomas** [comment]
My apologies. My initial search of npmjs for "marshal" didn't show this package in the top-5, so I didn't look further. Thanks @marcj !
